version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5050:5000"
    environment:
      - PASSWORD=${PASSWORD}
    read_only: true
    mem_limit: 256m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: secureuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    mem_limit: 256m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "secureuser"]
      interval: 30s
      timeout: 10s
      retries: 5

